version: '3.3'
services:
  # NGINX webservers with nginx-demo hello page
  nginx1:
      hostname: nginx1
      build: nginx-hello
      expose:
        - "80"     
  nginx2:
      hostname: nginx2
      build: nginx-hello
      expose:
        - "80"  
  nginx-app-protect:
      hostname: nginx-app-protect
      build: nginx-app-protect
      links:
          - nginx1:nginx1
          - nginx2:nginx2
      volumes:
          - ./nginx-app-protect/etc/nginx/conf.d:/etc/nginx/conf.d
      ports:
          - 8080:8080
          - 80:80
          - 443:443
          - protocol: udp
            published: 1053
            target: 53
      restart: always
  dns_bind:
    hostname: bind-01
    image: internetsystemsconsortium/bind9:9.11
    volumes: 
        - ./bind-base/etc/bind:/etc/bind
    expose:
        - "53"